Develop
ekip-s/java-explore-with-me pull request #2
Opened 2023-01-11 05:06 UTC by ekip-s

2023-01-13 17:01 UTC, Fleaman777 requested changes

2023-01-13 17:13 UTC, Fleaman777 commented
может показаться, что комментариев много, но на самом деле критичных нет, большинство связано с восприятием кода

2023-01-14 08:07 UTC, ekip-s commented on server/pom.xml
> +            <version>42.5.0</version>
я почитал про это. Перенес все зависимости в основной pom, но dependencyManagement  не стал использовать, так как у меня почти все зависимости одинаковые в модулях, получится нужно будет дублировать 2 раза. Так они в одном поме указаны.

2023-01-14 08:10 UTC, ekip-s commented on server/src/main/java/ru/practicum/service/CategoriesService.java
> +    private Category getBuId(long id) {
Я всю ночь писал код - так-что то, что он работает уже фантастика)

2023-01-14 08:13 UTC, ekip-s commented on server/src/main/java/ru/practicum/controller/admin/CategoriesAdminController.java
> +        return categoriesService.patchCategories(category);
тут поправил, гляну в остальных классах

2023-01-14 08:30 UTC, ekip-s commented on server/src/main/java/ru/practicum/service/CategoriesService.java
> +public class CategoriesService extends ValidationMaster {
валидаторы сделал отдельным классом, без наследования; (но оставил наследование между валидаторами, тут кажется все логично)

2023-01-14 08:34 UTC, ekip-s commented on server/src/main/java/ru/practicum/service/CompilationsService.java
> +        Compilations compilations1 = new Compilations(compilations, publishes);
вообще перенес в следующую строку.

2023-01-14 08:45 UTC, ekip-s commented on server/src/main/java/ru/practicum/service/PublishService.java
> +                .map(p -> new AnswerPublishDTO(p))
поправил

2023-01-14 09:09 UTC, ekip-s commented on server/src/main/java/ru/practicum/service/CompilationsService.java
> +        }
он и правда хороший, если о нем знать) 
поправил;

2023-01-14 09:18 UTC, ekip-s commented on server/src/main/java/ru/practicum/service/CompilationsService.java
> +    }
я по предыдущему комменту везде поправил.

2023-01-14 10:21 UTC, ekip-s commented on server/src/main/java/ru/practicum/service/RequestsService.java
> +    private Publish getPublish(long id) {
переименовал в принципе сущность в Publication

2023-01-14 10:22 UTC, ekip-s commented on server/src/main/java/ru/practicum/service/RequestsService.java
> +        }
поменял по комменту ранее везде

2023-01-14 10:35 UTC, ekip-s commented on server/src/main/java/ru/practicum/service/PublishService.java
> +    }
согласен

2023-01-14 10:53 UTC, ekip-s commented on server/src/main/java/ru/practicum/service/UserService.java
> +        if (ids == null) {
я чет думал там или передаешь инфу (и получается массив) либо не передаешь. (получается null) 
Я сделал доп. проверку.

2023-01-14 11:02 UTC, ekip-s commented on server/src/main/java/ru/practicum/service/PublishService.java
> +    private Publish essenceFilling(Publish publish, long userId) {
переименовал. Во всем виноват гугл переводчик, нужно было юзать яндекс-переводчик, если такой есть;

2023-01-14 11:06 UTC, ekip-s commented on server/src/main/java/ru/practicum/service/RequestsService.java
> +    public RequestDto cancellationApplicationPrivate(long eventId, long userId, long reqId) {
первое поменял. 
cancellationUserEvents - не нахожу, скорее всего ранее уже дропнул;

2023-01-14 11:22 UTC, ekip-s commented on server/src/main/java/ru/practicum/service/PublishService.java
> +        if (user.getId() != userid) {
я тупанул. Поправил.

2023-01-14 11:36 UTC, ekip-s commented on server/src/main/java/ru/practicum/validation/PublishValidationMaster.java
> +    }
оставил один с более общей ошибкой.

2023-01-14 11:41 UTC, ekip-s commented on server/src/main/java/ru/practicum/service/RequestsService.java
> +    public RequestDto approvalApplicationPrivate(long eventId, long userId, long reqId) {
поменял

2023-01-14 11:43 UTC, ekip-s commented on server/src/main/java/ru/practicum/validation/RequestValidationMaster.java
> +    }
пока оставлю так, подумаю в свободное время, сейчас сроки горят, нужно фичу сделать. 
На первый взгляд только очень сложные конструкции лезут как идеи. Их я делать не хочу.

2023-01-14 11:46 UTC, ekip-s commented on server/src/main/java/ru/practicum/service/RequestsService.java
> +        Request request1 = requestsRepository.save(request);
сделано

2023-01-14 11:50 UTC, ekip-s commented on server/src/main/java/ru/practicum/service/RequestsService.java
> +            publish.setParticipantLimit(publish.getParticipantLimit() - 1);
казалось по названию метода понятно, но вытащил в константу;

2023-01-14 11:51 UTC, ekip-s commented on server/src/main/java/ru/practicum/controller/user/PublicPublishController.java
> +        return publishService.getPublishPublic(text, categories, paid, rangeStart, rangeEnd, onlyAvailable, sort, from, size);
самому жутко, у меня на работе максимум 3 параметра; 
Не нашел как упростить;

2023-01-14 11:53 UTC, ekip-s commented on server/src/main/java/ru/practicum/controller/user/PublicPublishController.java
> +            System.out.println("Ошибка сервиса статистики.");
согласен, не доехал до этого;

2023-01-14 11:55 UTC, ekip-s commented on server/src/main/java/ru/practicum/exception/CustomError.java
> +public class CustomError {
На самом деле это был единственный вариант)) ( до других не доехал)

2023-01-14 12:05 UTC, ekip-s commented on stats-server/src/main/java/ru/practicum/StatsController.java
> +public class StatsController {
Я планировал сделать это в самом конце, но оч. долго e...лся с ошибкой 124, пока не почистлил все pom под 0; 
Когда все прошло, я уже просто пошел спать час и на работу))

2023-01-14 12:07 UTC, ekip-s commented on server/src/main/java/ru/practicum/exception/CustomError.java
> +public class CustomError {
комментов не много, ошибки правильные, спс, что обратил внимание.

2023-01-15 19:07 UTC, Fleaman777 commented on server/pom.xml
> +            <version>42.5.0</version>
ну да, ты все правильно сделал, нет смысла дублировать зависимости в помниках модулей, если можно указать ее в одном месте (основной пом)

мой комментарий был больше о том, что в помниках модулей есть зависимость postgresql с явным указанием одинаковой для 2х модулей версией,
хорошо было бы, что б эта версия была указана в 1 месте, т.е. в основном помнике

2023-01-15 19:09 UTC, Fleaman777 commented on server/src/main/java/ru/practicum/service/CategoriesService.java
> +public class CategoriesService extends ValidationMaster {
отличный вариант !

2023-01-15 19:14 UTC, Fleaman777 commented on server/src/main/java/ru/practicum/service/UserService.java
> +        if (ids == null) {
правильно поступил,

хоть на всевозможные кейсы тяжело придумать проверки, но основные точно можно закрыть

2023-01-15 19:16 UTC, Fleaman777 commented on server/src/main/java/ru/practicum/service/PublishService.java
> +    private Publish essenceFilling(Publish publish, long userId) {
есть) 
если что-то нужно перевести, обычно им и пользуюсь, нравится больше чем гугловский

2023-01-15 19:47 UTC, Fleaman777 approved these changes

2023-01-15 19:47 UTC, Fleaman777 commented on server/src/main/java/ru/practicum/service/PublicationService.java
> +        ValidationMaster.checkIds(id);
дело вкуса, 
но мне например больше нравится использовать статический импорт для статик методов, на мой взгляд так код выглядит чуть компактней, а значит и чуть читаемей 

если не пробовал, посмотри, может тебе тоже зайдет)

2023-01-15 19:47 UTC, Fleaman777 commented on server/src/main/java/ru/practicum/service/RequestsService.java
> +        return userRepository.findById(userId)
красота

2023-01-15 20:35 UTC, Fleaman777 commented
этот пр аппрвнул, можно смело делать фичу

только я что-то не знаю, что в ревьюилке с работой делать, завершать и ждать фичу в новой задаче, 
или отправить на доработку, и после сделанной фичи закрывать 

спрошу у своих,

2023-01-16 17:20 UTC, merged